/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSyncProgressRouteImport } from './routes/_authenticated/sync-progress'
import { Route as AuthenticatedSyncLogsRouteImport } from './routes/_authenticated/sync-logs'
import { Route as AuthenticatedPriceChangesRouteImport } from './routes/_authenticated/price-changes'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as ApiPublicPricesRouteImport } from './routes/api/public/prices'
import { Route as ApiPublicMachinesRouteImport } from './routes/api/public/machines'
import { Route as ApiPublicLookupRouteImport } from './routes/api/public/lookup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncProgressRoute =
  AuthenticatedSyncProgressRouteImport.update({
    id: '/sync-progress',
    path: '/sync-progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSyncLogsRoute = AuthenticatedSyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPriceChangesRoute =
  AuthenticatedPriceChangesRouteImport.update({
    id: '/price-changes',
    path: '/price-changes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPricesRoute = ApiPublicPricesRouteImport.update({
  id: '/api/public/prices',
  path: '/api/public/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMachinesRoute = ApiPublicMachinesRouteImport.update({
  id: '/api/public/machines',
  path: '/api/public/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLookupRoute = ApiPublicLookupRouteImport.update({
  id: '/api/public/lookup',
  path: '/api/public/lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/price-changes': typeof AuthenticatedPriceChangesRoute
  '/sync-logs': typeof AuthenticatedSyncLogsRoute
  '/sync-progress': typeof AuthenticatedSyncProgressRoute
  '/api/public/lookup': typeof ApiPublicLookupRoute
  '/api/public/machines': typeof ApiPublicMachinesRoute
  '/api/public/prices': typeof ApiPublicPricesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/price-changes': typeof AuthenticatedPriceChangesRoute
  '/sync-logs': typeof AuthenticatedSyncLogsRoute
  '/sync-progress': typeof AuthenticatedSyncProgressRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/lookup': typeof ApiPublicLookupRoute
  '/api/public/machines': typeof ApiPublicMachinesRoute
  '/api/public/prices': typeof ApiPublicPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/price-changes': typeof AuthenticatedPriceChangesRoute
  '/_authenticated/sync-logs': typeof AuthenticatedSyncLogsRoute
  '/_authenticated/sync-progress': typeof AuthenticatedSyncProgressRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/lookup': typeof ApiPublicLookupRoute
  '/api/public/machines': typeof ApiPublicMachinesRoute
  '/api/public/prices': typeof ApiPublicPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-docs'
    | '/price-changes'
    | '/sync-logs'
    | '/sync-progress'
    | '/api/public/lookup'
    | '/api/public/machines'
    | '/api/public/prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api-docs'
    | '/price-changes'
    | '/sync-logs'
    | '/sync-progress'
    | '/'
    | '/api/public/lookup'
    | '/api/public/machines'
    | '/api/public/prices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/api-docs'
    | '/_authenticated/price-changes'
    | '/_authenticated/sync-logs'
    | '/_authenticated/sync-progress'
    | '/_authenticated/'
    | '/api/public/lookup'
    | '/api/public/machines'
    | '/api/public/prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicLookupRoute: typeof ApiPublicLookupRoute
  ApiPublicMachinesRoute: typeof ApiPublicMachinesRoute
  ApiPublicPricesRoute: typeof ApiPublicPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync-progress': {
      id: '/_authenticated/sync-progress'
      path: '/sync-progress'
      fullPath: '/sync-progress'
      preLoaderRoute: typeof AuthenticatedSyncProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync-logs': {
      id: '/_authenticated/sync-logs'
      path: '/sync-logs'
      fullPath: '/sync-logs'
      preLoaderRoute: typeof AuthenticatedSyncLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-changes': {
      id: '/_authenticated/price-changes'
      path: '/price-changes'
      fullPath: '/price-changes'
      preLoaderRoute: typeof AuthenticatedPriceChangesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/prices': {
      id: '/api/public/prices'
      path: '/api/public/prices'
      fullPath: '/api/public/prices'
      preLoaderRoute: typeof ApiPublicPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/machines': {
      id: '/api/public/machines'
      path: '/api/public/machines'
      fullPath: '/api/public/machines'
      preLoaderRoute: typeof ApiPublicMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lookup': {
      id: '/api/public/lookup'
      path: '/api/public/lookup'
      fullPath: '/api/public/lookup'
      preLoaderRoute: typeof ApiPublicLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedPriceChangesRoute: typeof AuthenticatedPriceChangesRoute
  AuthenticatedSyncLogsRoute: typeof AuthenticatedSyncLogsRoute
  AuthenticatedSyncProgressRoute: typeof AuthenticatedSyncProgressRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedPriceChangesRoute: AuthenticatedPriceChangesRoute,
  AuthenticatedSyncLogsRoute: AuthenticatedSyncLogsRoute,
  AuthenticatedSyncProgressRoute: AuthenticatedSyncProgressRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicLookupRoute: ApiPublicLookupRoute,
  ApiPublicMachinesRoute: ApiPublicMachinesRoute,
  ApiPublicPricesRoute: ApiPublicPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
